### ISSUE TITLE
InitialRating cannot be zero?

### ISSUE THREAD

**Issue by dashawk** [antennaio/jquery-bar-rating#13]
Hi, I just tested your plugin and it works perfectly fine.

I just have one concern about the initial rating. Can we set the initial rating to zero? Or all the stars are not highlighted if the rating is zero?

Thanks

**Comment by sonictemplates** [comment]
<select id="example-square">
												<option value=""></option>
												<option value="1">1</option>
												<option value="2">2</option>
												<option value="3">3</option>
												<option value="4">4</option>
												<option value="5">5</option>
										</select>
