### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by dialogik** [antennaio/jquery-bar-rating#22]
I don't really get how to use this plugin. I included the `.min.js` file and added

    $(function() {
        $('.barrating').barrating();
    });

to my site. Now I added some select fields with `class="barrating"` but the only thing that happens is that the regular select field disappears. Do I have to add all the CSS stuff as seen in `examples/css/examples.css` as well?

**Comment by antennaio** [comment]
The rating widget is styled with CSS as demonstrated in the examples. Feel free to reuse the CSS or modify it to your needs.

**Comment by dialogik** [comment]
So that means if I'm not adding any CSS the widget is not working properly?

**Comment by antennaio** [comment]
Yes, you need to style the widget with CSS, it's meant to be flexible.

**Comment by dialogik** [comment]
Okay, thanks for the information, was just trying to figure that out.

Maybe you could add two information to the `README.md` (for you - as owner/developer - this is clear, but for new parties this is a very relevant information):

1. Use `.barrating()` on a `div` wrapper element (required).
2. Add some individual CSS styles (required).

**Comment by antennaio** [comment]
Good point, I will update the instructions.

**Comment by dialogik** [comment]
Thank you! And thanks for this lovely plugin, too :-)
