### ISSUE TITLE
Hover Callbacks

### ISSUE THREAD

**Issue by zukilover** [antennaio/jquery-bar-rating#23]
Hi, thanks for the nice plugin.

Is there any way that I can listen to mouse over events? I'd like to capture which value the user is hovering on, and dynamically add classes based on the value, for a parent element.

Let me know.

**Comment by antennaio** [comment]
Since the widget is just a bunch of A elements, this could be done in this way:

```javascript
$('#example-a').next('.br-widget').find('a').on('mouseover', function () {
  $('.yourSelector').addClass('yourClass');
});
```
