### ISSUE TITLE
How to set rating from script?

### ISSUE THREAD

**Issue by antoshib** [antennaio/jquery-bar-rating#28]
Hi! Please, how to set rating value after barrating from script?

I try
$("#sel1").barrating({onSelect:function(value, text){alert(value);}});

// bla..bla..
$("#sel1").prop("value", "3"); // no effect
$("#sel1").prop("value", "3"); // no effect
$("#sel1").prop("rating", "3"); // no effect

**Comment by antennaio** [comment]
Hi,

Try getting the latest update of the plugin and do it like this -

$('select').barrating();
...
$('select').barrating('set', value);

**Comment by antoshib** [comment]
Sorry, it has not effect too. Code works only if I insert "destroy" and initialize again, as this

$("select")
	.barrating("destroy")
	.prop("value", rating)
	.barrating();

**Comment by antennaio** [comment]
Destroying the plugin will work, but it will be more efficient to use the new `set` method.

See example B:
http://antenna.io/demo/jquery-bar-rating/examples/

**Comment by pilondev** [comment]
i cant set value too i just put this code

   $('.example').barrating('set', 5);

and doing nothing

**Comment by JhayEmDev** [comment]
Use an ID instead of the class. Even if the class is unique like `.my-class-2523` it didn't work in my case. So use `#my-id-2523`

`$('#my-id-2523').barrating('set', 5);`

**Comment by Hemanth089** [comment]
I am using id selector, but its not working. 

example 1:

```
$("#UserFieldAns_" + fieldId).barrating({
                        theme: 'bars-circle',
                        allowEmpty: true,
                        showValues: false,
                        showSelectedRating: false,
                        silent: true,
                        onSelect: function (value, text, event) {
                            event.preventDefault();
                            $("#UserFieldAns_" + fieldId).val(value);
                        }
                    });
                    $("#UserFieldAns_" + fieldId).barrating('set', "3");
```

example 2:
 ```
$("#UserFieldAns_" + fieldId).barrating({
                        theme: 'bootstrap-stars',
                        allowEmpty: true,
                        showValues: false,
                        showSelectedRating: false,
                        silent: false,
                        onSelect: function (value, text, event) {
                            event.preventDefault();
                            $("#UserFieldAns_" + fieldId).val(value);
                        }
                    });

                    $("#UserFieldAns_" + fieldId).barrating('set', 3);
```

bot examples set the values

**Comment by dummlutz** [comment]
It would not work on float data when I choose  fontawesome-stars-o theme, 
ex. :  $('.example').barrating('set', 4.5);
The way I do is reset data-current-rating, destroy, and re-init the barrating
