### ISSUE TITLE
Page reload issue when using the plugin on aspx pages

### ISSUE THREAD

**Issue by Dinac81** [antennaio/jquery-bar-rating#31]
Hi, 

When i implent this plugin in my .net application, the aspx page gets looped inside the page load function.
When I implement the plugin inside a html document, i don't have this issue.

Do you know what could cause this?

Thank You

**Comment by antennaio** [comment]
Hey,

I don't know how .net works and what could be causing this but will appreciate any debug info or PR if you happen to identify the problem.

**Comment by Dinac81** [comment]
Thank You for the fast response. The code that seems to trigger it is:  ('.rating-enable').trigger('click');

I am very bad at javascript and jquery, so i don't know how to fix it, but You can see the cause of the issue explained here: http://stackoverflow.com/questions/12319758/angularjs-clicking-a-button-within-a-form-causes-page-refresh.

"A button element with no type attribute specified represents the same thing as a button element with its type attribute set to "submit"". So i think the button enable is clicking continuosly causing the page to loop.

I managed to solve my problem by deleting the code that enabled and disabled the plugin, since i need it active all the time, but You can probably fix it.

Thank You for the great plugin, it is the best i saw so far, and I was searching a lot.

**Comment by antennaio** [comment]
Thanks a lot for the detailed explanation! I will attempt to fix this.
