### ISSUE TITLE
Should the select control update inside "ratingchange" event callback?

### ISSUE THREAD

**Issue by manpreetssethi** [antennaio/jquery-bar-rating#32]
```javascript
$elem.find('option[value="' + value + '"]').prop('selected', true);
```

**Comment by manpreetssethi** [comment]
I believe this can a bit misleading since the UI doesn't reflect the actual state of the select control, and besides the UI is only updated on "click" event.

**Comment by antennaio** [comment]
The select field value gets updated because of 2 reasons:
- the value has to be available on form submit
- the select field is set to correct value when the widget is destroyed

Let me know how you would like to improve on that.

**Comment by antennaio** [comment]
Ok, I am closing this for now, please reopen the issue if you feel this needs to be clarified.
