### ISSUE TITLE
Bootstrap 3 Tooltips ?

### ISSUE THREAD

**Issue by techmantoolz** [antennaio/jquery-bar-rating#33]
Hi all

I'd like to use / display bootstrap tooltips (rather than use an additional 3rd party tooltip library) on individual elements. Any pointers on how / if this can be done ? (I did see a closed thread relating to using tooltipster - but can't apply same method to bootstrap)

TIA

T

**Comment by antennaio** [comment]
Hey, try this:

```javascript
$('.rating-a a:nth-child(1)').tooltip({ 'title': 'I am a tooltip' });
```

Where `.rating-a` is the container element of the rating.

**Comment by swrobel** [comment]
Here's what worked for me:
```javascript
$('.br-widget a').tooltip({title: function() { return this.dataset.ratingText }})
```
