### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by garygreen** [antennaio/jquery-bar-rating#34]
It would be cool to add a `themes` folder which contains various CSS files for different themes. One for FontAwesome, Bootstrap 3, CSS3, etc.

That would solve the only tedious thing about this plugin (that you have to manually write CSS just to make it useable, or copy example from the docs, manual work involved.)

I know themes is subjective, but at least have some 'sane' defaults so people can see and make it easier to get going straight out the box? What do you think? :smile:

**Comment by antennaio** [comment]
Agreed. The plugin requires at least a minimum of CSS to work.

Making it easier to get going with some ready made defaults or themes would be a good improvement...

**Comment by garygreen** [comment]
Will do a PR in a moment

**Comment by antennaio** [comment]
Thanks Gary,

Please give me some time to review your PR. I will consider to move the CSS I use on the [examples page](http://antenna.io/demo/jquery-bar-rating/examples/) to this new format.
