### ISSUE TITLE
Add ability to have no rating

### ISSUE THREAD

**Issue by garygreen** [antennaio/jquery-bar-rating#38]
At the moment when you initialize the rating it will always show as e.g. 1 star selected. This gives a false impression that the user has already rated when in fact they haven't.

You can get around this by adding a hidden option that is selected like:

```
<select>
	<option value="" selected disabled hidden></option>
	<option value="1">1</option>
	<option value="2">2</option>
	...
</select>
```

But this feels a bit clunky, it should be easier to do in the plugin itself. Maybe a new option like `allowEmpty` could simulate the above in the plugin itself. What do you think?

**Comment by antennaio** [comment]
It's actually the expected way of allowing for empty ratings... May need to be documented more explicitly though.

I considered adding an `allowEmpty` or similar option in the past, but in the end decided that it's better to rely on select field markup. If you look at Example C and play around with enable/disable button you'll see the select field and rating widget are kept in sync. I think that couldn't be easily done if the empty rating wasn't defined in the markup.

http://www.antenna.io/demo/jquery-bar-rating/examples/

**Comment by garygreen** [comment]
> I think that couldn't be easily done if the empty rating wasn't defined in the markup.

What I was thinking was the `allowEmpty` would basically just add the `<option ..>` empty field automatically to the markup during initialization, either at the beginning or end depending on if `reverse`.

**Comment by antennaio** [comment]
Ok, it could work as you described it... Essentially there would be two ways of allowing for empty ratings - either by having it defined on the select field or by setting the option.

**Comment by bhanwarpsrathore** [comment]
@antennaio Have you worked on the `allowEmpty` thing

**Comment by antennaio** [comment]
Not yet, but it's more of a nice-to-have feature - the same effect can be achieved by adding an empty option to the select field as described in the FAQ:

http://antenna.io/demo/jquery-bar-rating/examples/#nav-faq

**Comment by antennaio** [comment]
I added an `allowEmpty` option.

By default it is set to `null`, which means that the plugin will look for an option with empty value and if it's present it will assume that empty ratings are allowed (just like it worked until now).

**Comment by garygreen** [comment]
Looks good :+1:
