### ISSUE TITLE
$.data

### ISSUE THREAD

**Issue by garygreen** [antennaio/jquery-bar-rating#39]
The plugin makes heavy use of storing data inside $.data such as `.currentRatingValue` `.currentRatingText` `.userOptions` is there any significant reason why this can't be stored on the `BarRating` instance itself?

I'm happy to do a PR to change this but just wondered if this is a design preference or some use for accessing these values directly from `.data` as oppose to through the plugin API itself?

**Comment by antennaio** [comment]
Thanks for your PRs and input so far.

Storing data inside $.data on elements helped to manage state when the plugin is rerun on an element with a method such as set/clear/destroy. If you wish to modify the plugin to store all the state on BarRating instance instead it will be a good improvement.

**Comment by garygreen** [comment]
With `destroy` imo it should't no longer remember the state as it's all been destroyed. I can see it's useful on the examples but to be honest in practical real-world apps I can't really envisage a scenario where you would call .destroy and re-initialize expecting it to keep all existing state. It's possible to keep state even if you did store data on the BarRating instance itself anyway.

**Comment by garygreen** [comment]
Also wouldn't it keep the selected state anyway, as it selects the value on the `<select>`?

**Comment by antennaio** [comment]
Sure, if you think we can do without storing any data on elements, please go for it.

**Comment by curiosity26** [comment]
+1

A perk to moving away from $.data is that you could then use $.data to leverage the JS Data API to set options:

```html
<div data-barrating data-barrating-theme="font-awesome-stars" data-barrating-readonly>
<select><!-- ... --></select>
</div>
```

If the data api is already implemented, then please ignore. I checked the source code but didn't see its implementation. However, it's late and I've been looking at code for over 14 hours today. My eyes are a little tired. :-)
