### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by garygreen** [antennaio/jquery-bar-rating#42]
Are you planning on releasing a new version for the changes in master (themes?) :smile:

**Comment by antennaio** [comment]
Hi Gary

A new release is long overdue - I'll update the docs, repackage my own themes and make a new release by the end of the week.

**Comment by garygreen** [comment]
Cheers buddy, appreciate all the work! :smile:

**Comment by antennaio** [comment]
Pushed a new release. Themes will be a nice new feature... :)
