### ISSUE TITLE
Add ability to display value on bar rating and text on the side

### ISSUE THREAD

**Issue by zeeLondon** [antennaio/jquery-bar-rating#43]
At the moment it is possible to show the rating on the side of the control.

It would be good to have the possibility to show the value on actual bars and text (description) on the side (use the html select value/text items).

**Comment by garygreen** [comment]
You can already do this by adding a `data-html` attribute to your `<option>`.

**Comment by antennaio** [comment]
See the 'showValues' option @zeeLondon.

If additionally you'd like the option values to differ from what is displayed on the bars you can use `data-html` attribute on your `<options>` like Gary already mentioned.
