### ISSUE TITLE
Make it work with form validation aka .validate()

### ISSUE THREAD

**Issue by kevinfilteau** [antennaio/jquery-bar-rating#45]
Because the real field is hidden, jQuery validation don't work. So I temporary changed this line:

    self.$elem.hide();

With this maybe ugly code:

    self.$elem.css('position', 'absolute');
    self.$elem.css('left','-9999px');

Then now the field is not visible, but not hidden and the validation works.

Maybe you'll have a better way?

Thanks

**Comment by garygreen** [comment]
Honestly, validation libraries that only let you validate visible fields are stupid. You should take it up with whatever validation library your using. It's not something jquery bar rating should support.

**Comment by kevinfilteau** [comment]
It's this one. Do you know a better one that will work? http://jqueryvalidation.org/reference/ Thanks.

**Comment by garygreen** [comment]
Haven't checked the code for jquery validation so it may be possible to validate hidden fields. You may be interested in a validator I've created called [dominar](https://github.com/garygreen/dominar). It's based on Bootstrap but you pretty easily add "bootstrap style" css support for form validation even if your not using bootstrap specifically.

**Comment by kevinfilteau** [comment]
Thanks!

**Comment by kevinfilteau** [comment]
Fixed. It was a settings issue. Thank you for your time.

**Comment by DarthSonic** [comment]
> Fixed. It was a settings issue. Thank you for your time.

How did you fix it?
