### ISSUE TITLE
How to fix the bar rating when clicked by user?

### ISSUE THREAD

**Issue by q2apro** [antennaio/jquery-bar-rating#46]
The recent demos at http://antenna.io/demo/jquery-bar-rating/examples/ show only the changes of values when the user moves his mouse on the fields. 

The "normal" user case that s/he clicks on the selected item and then moves out the mouse cannot be found. But it is needed. Reason: When the user clicks on 3 / 5 he expects the value to be fixed, but when he moves the mouse outside, the value is changing. 

1. So how can I fix the value of the bar as soon as a click appears? 

2. And how to reapply another value when another click appears? 

3. Woraround could be to only react on clicks.

Thanks for your help.

**Comment by antennaio** [comment]
I added a new option `hoverState` that will let you achieve what you want by setting it to false.

**Comment by q2apro** [comment]
`$('.barratings').barrating({ hoverState:false });`

works. Thanks a lot.
