### ISSUE TITLE
Use images instead of backgrounds

### ISSUE THREAD

**Issue by jehy** [antennaio/jquery-bar-rating#47]
Hello! This is the best plugin I've seen for ratings, but it would be very cool to add support for using images instead of backgrounds. I need it because backgrounds don't get printed and I have to force all graphic to images... I made changes to plugin but it looks rather ugly and I'd like to use the latest version of your plugin in future...

**Comment by antennaio** [comment]
I'm not a fan of using images instead of css (or icon fonts) for ratings.

But you touched on an interesting problem. I added print styles to the demo page to see how printing could be supported. You can have a look at it and maybe it will help in your case.

**Comment by jehy** [comment]
Hello! I am also not a fan but that's the only way. Unfortunaly, no CSS solutiuons will work - I tried everything. You can take a look at http://stackoverflow.com/questions/5949897/how-to-get-a-background-image-to-print-using-css

The only way to print background images is to force user to manually set this option in browser (which is rather solution), that's why I had to use images instead of backgrounds.

But... Ilooked at your demo page and suddenly understood the solution. For stars, you use font with appropriate images... And it works! I will also make my font with images I need :)
Thanks! :+1:
