### ISSUE TITLE
Make callback optional when using set method

### ISSUE THREAD

**Issue by jehy** [antennaio/jquery-bar-rating#50]
Hello! I show user some rating with pre-initialized values. I initialize them using  **('select').barrating('set', value);** method and I don't want it to trigger any callback, I need callback only when user himself clicks rating. Could you make an option to disable callback when using  **$('select').barrating('set', value);** metod?

**Comment by jehy** [comment]
And just for fun - here's what I've done with the help of your rating plugin:

![charsheet](https://cloud.githubusercontent.com/assets/2296742/10659655/05cf2bfa-78aa-11e5-838f-747b47c14191.png)

**Comment by antennaio** [comment]
Looks phantastic @jehy 

You are the second person to request that the callbacks are not fired when the rating is controlled with the `set` method. The `silent` option will help in your case I think. You can try it out by getting the plugin from master.

**Comment by jehy** [comment]
Thanks!
