### ISSUE TITLE
Accessibility: allow tabbing to update text

### ISSUE THREAD

**Issue by NeilJS** [antennaio/jquery-bar-rating#51]
Hi.
Currently, when using TAB to navigate, the widget does allow us to select bars and set them but it doesn't also update the text.

Suggest something like the following to enable this (line 212)

     // handle mouseenter events

            var attachMouseEnterHandler = function($all) {
                $all.on({
                    mouseenter: function() {
                        ...
                    },
                    focus: function() {
                        $(this).trigger("mouseenter");
                    },
                    blur: function() {
                        $(this).trigger("mouseleave");
                    }
                });
            };

**Comment by antennaio** [comment]
Thanks for reporting @NeilJS.

Tabbing through the ratings will show selected rating next to the widget now.

**Comment by NeilJS** [comment]
Great, thanks. Any chance you can create a new release? I'm using bower that will only pull v1.1.3 which is a few commits behind.

I've manually tested the update though and it's fine.
Thanks

**Comment by antennaio** [comment]
It's a little to early for a new release.

Please switch to master in bower.json:

```
"dependencies": {
  "jquery-bar-rating": "master"
}
```

Or install the plugin with:

`bower install jquery-bar-rating#master --save`

**Comment by NeilJS** [comment]
OK, good call. Thanks
