### ISSUE TITLE
Request For decimals 

### ISSUE THREAD

**Issue by technofreaky** [antennaio/jquery-bar-rating#52]
@antennaio 
Thanks for the wonderful plugin :) i really love it.

i am just using your plugin in one of my free plugin.
i just wanted to know its possible to set decimals rating. as my plugin requires decimals rating.
if not can you just give me a patch code for it ?

But i really love your work :) 
Thanks
varun s

**Comment by antennaio** [comment]
Hi @technofreaky

I considered partial ratings in the past, but decided to keep this plugin rather simple. The good thing is that there are other alternatives that provide this kind of functionality if you look on GitHub.

**Comment by technofreaky** [comment]
@antennaio .. i know.. i am very thank full to you.. i have just made a plugin for woocommerce with your script.

http://codecanyon.net/item/advanced-product-reviews-for-woocommerce/14323430

If you provide half star / decimal star rating it would nice.. you can even give me the code which supports it.. or no issues. and 1000 of thanks for your hardwork. in this rating system
