### ISSUE TITLE
Click doesn't fire onSelect, after changing readonly to true and then revert to false

### ISSUE THREAD

**Issue by zimarai** [antennaio/jquery-bar-rating#53]
I fixed this changing line 241 in jquery.barrating.js file from
```
self.options.onSelect.call(
```
to
```
var options = getData('userOptions');
options.onSelect.call(
```
I don't know if this is the best solution, but it works. 
Does anyone knows why self.options.onSelect shows an empty function after changing readonly values to true and then to false?

**Comment by zimarai** [comment]
I made a pull request
https://github.com/antennaio/jquery-bar-rating/pull/54

**Comment by antennaio** [comment]
Good catch, thanks @zimarai 

In this case self.options was referencing the default plugin options instead of user's options.
