### ISSUE TITLE
bar rating gets removed after clicking data-filter attribute.

### ISSUE THREAD

**Issue by vinothrao** [antennaio/jquery-bar-rating#55]
please refer the following site:http://yaazhxenomics.azurewebsites.net/

in this once i moved from All tab the star rating gets removed. I couldn't get  why this is happening.Please help.

**Comment by antennaio** [comment]
Hello @vinothrao

It looks like each time a tab is opened the content gets reloaded in the background - you will have to find a way to initialise the plugin on tab change.
