### ISSUE TITLE
Half points for starvotes

### ISSUE THREAD

**Issue by jedoStyle** [antennaio/jquery-bar-rating#56]
can you add please the option for half star in the starvoting function ?

**Comment by mkranitz** [comment]
Why not double the stars?

**Comment by binskeep** [comment]
What I need is to being able to display 1/4, 1/2, 3/4 stars, displaying the rough average of all of the reviewers.  Each reviewer needs to be able to select 'whole' stars though.

**Comment by baladkb** [comment]
Hi @antennaio,
First of all thanks for this plugin :+1:, it's different form other rating plugins.
I'm also Expecting the Fraction value like 3.5, 2.7, 1.3, 0.7 etc.. 
If You point me where I want to do changes to achieve this kind I'll try form my side.

**Comment by pvin** [comment]
@antennaio @baladkb Im also expecting the same functionality. Can you please direct me on float type value.

**Comment by antennaio** [comment]
Ok, I will have something ready after the weekend.

**Comment by baladkb** [comment]
@antennaio  Ok thanks.

**Comment by antennaio** [comment]
I added support for half-stars when displaying ratings - there is a sample implementation included -

http://antenna.io/demo/jquery-bar-rating/examples/

You can try out the feature by getting the plugin from master branch.

**Comment by pvin** [comment]
@antennaio Thank you.

**Comment by baladkb** [comment]
@antennaio thanks :+1: 
If possible to add 5.9 like below image
![untitled-2](https://cloud.githubusercontent.com/assets/4152211/15566467/ceb8f5fc-233e-11e6-89ed-af397f70e577.png)

**Comment by d9onis** [comment]
Hi.
@antennaio please update npm package with this fix.

**Comment by antennaio** [comment]
@baladkb Currently fractional ratings are marked with `br-fractional` and `br-fractional-*` css classes (where * is 10, 20, 30...). This should allow to build the kind of themes you are going after by using custom icon fonts or SVG.

@d9onis A new release is available on npm (1.2.0) - please take a quick look at the CHANGELOG before installing it.

**Comment by d9onis** [comment]
Thank you!

**Comment by baladkb** [comment]
thanks @antennaio!
