### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by seanrockster** [antennaio/jquery-bar-rating#57]
just displays a 1 and thats it.

**Comment by mkranitz** [comment]
I am having the same issue

**Comment by antennaio** [comment]
Hello,

Can you include some more information, maybe a jsfiddle or jsbin or a link that reproduces your problem?

Do these demos work for you?
http://www.antenna.io/demo/jquery-bar-rating/examples/

**Comment by mkranitz** [comment]
Thanks, but I moved to a different solution.

____________________________

Michael Kranitz, CEO
*Eventsquid.com*
www.linkedin.com/in/kranitz

www.Eventsquid.com <http://www.eventsquid.com/>
www.Golfsquid.com <http://www.golfsquid.com/>
www.Fitsquid.com
www.Flightsquid.com
www.ArcheryEvents.com <http://www.archeryevents.com/>
www.RCFlightDeck.com <http://www.rcflightdeck.com/>
www.RCCarEvents.com <http://www.rccarevents.com/>
www.GunShootingEvents.com <http://www.gunshootingevents.com/>


720.838.0700 (mobile)

"Skate to where the puck is going, not where it's been" -- Wayne Gretzky

Watch the EventSquid video:
<https://www.youtube.com/watch?v=M2d032RXNXo>

**Comment by antennaio** [comment]
Ok, I added a few more details to the installation instructions to make them more complete, hopefully removing any ambiguities when setting up the plugin for the first time.
