### ISSUE TITLE
How to pass data to callback?

### ISSUE THREAD

**Issue by manubellido** [antennaio/jquery-bar-rating#60]
Hi, probably very naive question. How do I pass data to the callback method?

I would like to make an AJAX call to an API on select and clear methods, but I am trying to figure out how to pass information necessary for the API call. 

Since content can be generated automatically, I usually set ids for ajax calls in the elements. For example:  `<button id="myButton" data-id="10"> </button>`
and then I can access that id in jquery. But I can't do this with bar-rating since it replaces the default select element.

Any hints would be appreciated!

**Comment by antennaio** [comment]
Hi,

There's nothing stopping you from accessing the select field:

```
$('#example-pill').barrating('show', {
  theme: 'bars-pill',
  onSelect: function (value, text) {
    var id = $('#example-pill option:selected').data('id');
    console.log(id);
  }
});
```

Hope this helps.

**Comment by manubellido** [comment]
Thanks for your reply. 

I got stuck when there are multiple items to be rated. Then I need to be able to get the data from a specif option on a specific select. Let's say that the ids are of the form: example-pill-{{number}}, I tried this and gets the first select data, since the callback won't know which select was picked.

$('[id^=example-pill]').barrating('show', {
  theme: 'bars-pill',
  onSelect: function (value, text) {
    var id = $('[id^=example-pill] option:selected').data('id');
    console.log(id);
  }
});

**Comment by antennaio** [comment]
There are many ways to do that, you need to use the field with the correct #id in your callback or access `this.$elem` if that makes it more convenient -

```
onSelect: function (value, text) {
  console.log(this.$elem.find('option:selected').data('id'));
}
```

**Comment by manubellido** [comment]
thanks for the help!

**Comment by marwan2** [comment]
Your solution is print "undefined"

$('#example-pill').barrating('show', {
  theme: 'bars-pill',
  onSelect: function (value, text) {
    var id = $('#example-pill option:selected').data('id');
    console.log(id);
  }
});

So it doesn't work !!!!!

**Comment by duffett** [comment]
The following worked for me
HTML:
```
<select class="priority-widget" data-field-name="a">
   <option>1</option>
   <option>2</option>
</select>
<select class="priority-widget" data-field-name="b">
   <option>1</option>
   <option>2</option>
</select>
```

Script:
```
$('.priority-widget').barrating({
  theme: 'bars-pill',
  onSelect: function (value, text) {
    var fieldValue= this.$elem.data().fieldName;
     // a or b
    console.log(fieldValue);
  }
}); 
```
