### ISSUE TITLE
How can i implement fractional ratings

### ISSUE THREAD

**Issue by morris014** [antennaio/jquery-bar-rating#63]

**Comment by massivemassage** [comment]
Use fontawesome-stars-o.css (the hollow ones) and just set a fractional initial value.

**Comment by antennaio** [comment]
Exactly, the `fontawesome-stars-o` theme is currently the only ready-made theme that you can use to display a fractional rating. It's making use of the following icons:

http://fontawesome.io/icon/star-o/
http://fontawesome.io/icon/star-half-o/
