### ISSUE TITLE
ability to show both user rating and average rating

### ISSUE THREAD

**Issue by pgeez** [antennaio/jquery-bar-rating#64]
Is there a way to show the rating value selected by a User and _also_ show the average rating from all Users?

I tried adding a custom `onSelect` listener that attaches special CSS classes to the `<a>` elements based on their value with respect to some external average, **but** the call to `resetStyle` wipes **all** CSS classes and makes this impossible.

https://github.com/antennaio/jquery-bar-rating/blob/master/jquery.barrating.js#L216-L218

Thanks.

**Comment by antennaio** [comment]
I changed it so that now all br-* classes are wiped instead. Hope this helps.
