### ISSUE TITLE
R Shiny htmlwidget

### ISSUE THREAD

**Issue by harveyl888** [antennaio/jquery-bar-rating#67]
Thanks for a great rating widget @antennaio .  I've wrapped the javascript and themes into an htmlwidget for use in R Shiny apps.  The code can be found at [https://github.com/harveyl888/barRating](https://github.com/harveyl888/barRating).
.

**Comment by antennaio** [comment]
Wow, that's really great @harveyl888, looking forward to play with it to see how it works.

I will look for a good place to reference your integration with Shiny somewhere (maybe FAQ and/or README).

**Comment by harveyl888** [comment]
Thanks.  Like I said - a really useful widget.  I'd put together a tool for a number of reviewers to comment on and rate posters for a conference we're putting together.  I found **jquery-bar-rating** whilst searching for a way to add a score and it integrated nicely.  Thanks again!
