### ISSUE TITLE
Scaling via CSS

### ISSUE THREAD

**Issue by TechTreeDev** [antennaio/jquery-bar-rating#69]
Is it possible to change the size via CSS or better as option in the JS?

Because every attempt to change the 21px (font-awesome-o )height didn't work.

It only works generally, if the class `
 .br-theme-fontawesome-stars-o .br-widget a {
    font: normal normal normal 20px/1 FontAwesome; 
....}`

is changed, but i need at least 3 sizes.

I would be optimal, if there could be a JS parameter like this:
`size: '10'px,`

**Comment by antennaio** [comment]
Please adjust the font property instead of height - example:

small
`font: normal normal normal 20px/1 FontAwesome;`

large
`font: normal normal normal 40px/1 FontAwesome;`

**Comment by antennaio** [comment]
Hi @TechTreeDev

I've seen you edited your original question. There will be no 'size' option added, the ratings are meant to be styled with CSS.

**Comment by TechTreeDev** [comment]
Okay, as far as I have tried it's only possible to change it for all, or am I wrong?
I have defined a class with:
`font: normal normal normal 14px/1 FontAwesome !important;`
And wrapped it arround the ratings that should be smaller. But they're still as big as the rest.
It may sound stupid, I know, but can you explain, how I can use multiple sizes simultaneously?

**Comment by antennaio** [comment]
Should be possible, just make sure the CSS rule is specific enough:

```
.your-wrapper-class .br-theme-fontawesome-stars-o .br-widget a {
  font-size: 14px;
}
```

**Comment by TechTreeDev** [comment]
Dang, forgot the "-o" ._.
Thank you (nice work, though)
