### ISSUE TITLE
How to set a fractional rating using the set-method?

### ISSUE THREAD

**Issue by quings** [antennaio/jquery-bar-rating#70]
It works to set a fractional rating via 

$('#my_rating').barrating({
        theme: 'fontawesome-stars-o',
        initialRating: 3.4,
       
but using the set-method in the following way:

$('#my_rating').barrating('set', 3.4);

does not work with fractional numbers. What kind of mistake am I doing?

**Comment by antennaio** [comment]
When you are using the `set` method you need to specify a value that exists in the underlying select field.
