### ISSUE TITLE
How is Pill Rating intial value (A) selected ?

### ISSUE THREAD

**Issue by malarv09** [antennaio/jquery-bar-rating#73]
http://antenna.io/demo/jquery-bar-rating/examples/

In the above link, how is the initial value (A) selected by default in  Pill Rating (4th Rating) ? I cant find any coding for this. Other rating has selected attribute. I would like to retain values if someone does the refresh.

**Comment by antennaio** [comment]
If `initialRating` option is not set and the select field doesn't have any options marked with  **selected="selected"** the plugin will default to the first rating.

To save the selected rating and keep its value after page refresh you'd need to store the value in the database, session, cookie or local storage. It's something you have to do on your own.
