### ISSUE TITLE
Could we have an option to treat 0 (zero) as an empty rating?

### ISSUE THREAD

**Issue by primehalo** [antennaio/jquery-bar-rating#75]
I know that we can have empty ratings by making the first option an empty string, but I would like the option to use zero instead of an empty string for an empty rating.

I accomplished this by adding a new option, emptyVal, which can be set to zero or any other value you want to be considered empty. Then I created a method to determine if the value is empty:
```
            var isValEmpty = function(val) {
				return !val || (self.options.hasOwnProperty('emptyVal') && val == self.options.emptyVal);
            }
```
I used this in the following two places:
```
                    // first OPTION empty - allow deselecting of ratings
                    deselectable: (isValEmpty(self.$elem.find('option:first').val())) ? true : false
```
```
                    // create ratings - but only if val is defined
                    if (!isValEmpty(val)) {
```

**Comment by antennaio** [comment]
Hey @primehalo

Why would you like to use zero instead of an empty string for an empty rating? I'm trying to think about how that might be useful?

**Comment by primehalo** [comment]
I have PHP functions that build the form fields from a list of predefined data such as arrays of key/value pairs where the key can be 0 to 10. Those key/value arrays are used elsewhere so I can't change them to start with an empty string and then continue from 1 to 10. I know I could copy the array and change the zero to an empty string and then back to zero again when needed, but it's much simpler to just specify I want zero to be an empty rating.

**Comment by antennaio** [comment]
I just added `allowEmpty` setting to the plugin (on master branch), which together with `emptyValue` could be what you need:

```
$('#example-pill').barrating('show', {
  theme: '...',
  allowEmpty: true,
  emptyValue: 0
});
```
