### ISSUE TITLE
Fastclick error

### ISSUE THREAD

**Issue by KarnakMeo** [antennaio/jquery-bar-rating#87]
The fastclik option doesn't work.
It seem to be an error on the code for the option of fastclick, you call fastClicks function instead of fastClicks user option.

I found error in the line 402 and I correct it using

`                if (getData('userOptions').fastClicks) {
                    fastClicks($elements);
                }
`

instead of

`                if (fastClicks) {
                    fastClicks($elements);
                }
`

I hope I have been helpful. I'm sorry for my bad english ..

**Comment by antennaio** [comment]
Thanks @KarnakMeo, great catch, fixed that.
