### ISSUE TITLE
set InitialRating for multiple select

### ISSUE THREAD

**Issue by aghayeff** [antennaio/jquery-bar-rating#91]
I have multiple select box which comes from database. I added "data-current-rating" to select option. But, can't set initial rating using this option.    
```

<select class="stars" data-current-rating="3.5">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
<option value="5"></option>
</select>

<select class="stars" data-current-rating="4.4">
<option value="1"></option>
<option value="2"></option>
<option value="3"></option>
<option value="4"></option>
<option value="5"></option>
</select>
```

```
$('.stars').barrating('show', {
        theme: 'fontawesome-stars-o',
        emptyValue: 0,
        readonly: true,
        initialRating: $(this).data('current-rating')
    });
```

Of course, I can set initialRating value from `option selected`, but due to case, I will not able to display fractional star.

**Comment by mdefrancq** [comment]
Hi,
did you find a solution ? I'm having the same problem

**Comment by aghayeff** [comment]
@mdefrancq , unfortunately, no

**Comment by jfelipelopez** [comment]
Try using attr insted of data to get the data-current-rating value, like this.
`$('.stars').barrating('show', {
        theme: 'fontawesome-stars-o',
        emptyValue: 0,
        readonly: true,
        initialRating: $(this).attr('data-current-rating')
    });`

**Comment by mdefrancq** [comment]
@jfelipelopez thank you but it doesn't work.

**Comment by timgavin** [comment]
@mdefrancq Try this; works for me.

```
<select id="ratings" name="rating" data-current-rating="2">
	<option value="1">1</option>
	<option value="2">2</option>
	<option value="3">3</option>
	<option value="4">4</option>
	<option value="5">5</option>
</select>

<script>
    $(function() {
        $('#ratings').barrating({
            theme: 'fontawesome-stars',
            initialRating: $('#ratings').data('current-rating'),
        });
    });
</script>
```

**Comment by Nick513** [comment]
Having the same problem, anyone know a workaround for this?

**Comment by ChetanGoti** [comment]
Try this. (as I mentioned at https://github.com/antennaio/jquery-bar-rating/issues/99#issuecomment-346353975)

```
$('.stars').each(function(index, el) {
  var $El = $(el);
  $El.barrating({
    theme: 'fontawesome-stars-o',
    initialRating: $El.attr('data-current-rating') 
  });
});
```

**Comment by aghayeff** [comment]
@ChetanGoti  as mentioned, works perfect! Thank you!
